<?php

function sga_filter_info() {
  $filters = array();
  $filters['sgafilter'] = array(
    'title' => t('set manifest'),
    'description' => t('Sets manifest'),
    'process callback' => 'sga_set_manifest',
    'cache' => FALSE 
  );
  return $filters;
}

function sga_set_manifest($text, $filter) {
  $node = menu_get_object();
  $manifest = field_get_items('node',$node, 'field_manifest');
  $m = $manifest[0]['value'];
  return str_replace('[MANIFEST]', $m, $text);
}