// Generated by CoffeeScript 1.3.3

/*
# SGA Shared Canvas v0.0.1
#
# **SGA Shared Canvas** is a shared canvas reader written in CoffeeScript.
#
#  
# Date: Tue Dec 4 16:33:20 2012 -0500
#
# License TBD.
#
*/


(function() {
  var __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  (function($, MITHGrid) {
    MITHGrid.globalNamespace("SGA");
    return SGA.namespace("Reader", function(SGAReader) {
      SGAReader.namespace("Data", function(Data) {
        Data.namespace("TextStore", function(TextStore) {
          return TextStore.initInstance = function() {
            var args;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return MITHGrid.initInstance.apply(MITHGrid, __slice.call(args).concat([function(that) {
              var fileContents, loadingFiles, options, pendingFiles;
              options = that.options;
              fileContents = {};
              loadingFiles = {};
              pendingFiles = {};
              that.addFile = function(files) {
                var file, _i, _len, _results;
                if (!$.isArray(files)) {
                  files = [files];
                }
                _results = [];
                for (_i = 0, _len = files.length; _i < _len; _i++) {
                  file = files[_i];
                  _results.push((function(file) {
                    if ((file != null) && !(fileContents[file] != null) && !(loadingFiles[file] != null)) {
                      loadingFiles[file] = [];
                      return $.ajax({
                        url: file,
                        type: 'GET',
                        processData: false,
                        success: function(data) {
                          var c, f, _j, _len1, _ref;
                          c = data.documentElement.textContent;
                          fileContents[file] = c;
                          _ref = loadingFiles[file];
                          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
                            f = _ref[_j];
                            f(c);
                          }
                          return delete loadingFiles[file];
                        }
                      });
                    }
                  })(file));
                }
                return _results;
              };
              return that.withFile = function(file, cb) {
                if (fileContents[file] != null) {
                  return cb(fileContents[file]);
                } else if (loadingFiles[file] != null) {
                  return loadingFiles[file].push(cb);
                }
              };
            }]));
          };
        });
        return Data.namespace("Manifest", function(Manifest) {
          var NS;
          NS = {
            "http://dms.stanford.edu/ns/": "sc",
            "http://www.shared-canvas.org/ns/": "sc",
            "http://www.w3.org/2000/01/rdf-schema#": "rdfs",
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#": "rdf",
            "http://www.w3.org/2003/12/exif/ns#": "exif",
            "http://purl.org/dc/elements/1.1/": "dc",
            "http://www.w3.org/ns/openannotation/core/": "oa",
            "http://www.openannotation.org/ns/": "oa",
            "http://www.w3.org/ns/openannotation/extension/": "oax",
            "http://www.openarchives.org/ore/terms/": "ore",
            "http://www.shelleygodwinarchive.org/ns/1#": "sga",
            "http://www.shelleygodwinarchive.org/ns1#": "sga"
          };
          return Manifest.initInstance = function() {
            var args;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return MITHGrid.initInstance.apply(MITHGrid, ["SGA.Reader.Data.Manifest"].concat(__slice.call(args), [function(that) {
              var data, importFromURL, itemsWithType, loadedUrls, options;
              options = that.options;
              data = MITHGrid.Data.Store.initInstance();
              that.size = function() {
                return data.size();
              };
              loadedUrls = [];
              importFromURL = function(url, cb) {
                if (__indexOf.call(loadedUrls, url) >= 0) {
                  cb();
                  return;
                }
                loadedUrls.push(url);
                that.addItemsToProcess(1);
                return $.ajax({
                  url: url,
                  type: 'GET',
                  contentType: 'application/rdf+json',
                  processData: false,
                  dataType: 'json',
                  success: function(data) {
                    return that.importJSON(data, cb);
                  },
                  error: cb
                });
              };
              that.importJSON = function(json, cb) {
                var items, s, subjects, syncer;
                items = [];
                syncer = MITHGrid.initSynchronizer(function() {
                  that.addItemsProcessed(1);
                  return setTimeout(function() {
                    var item, _i, _len;
                    for (_i = 0, _len = items.length; _i < _len; _i++) {
                      item = items[_i];
                      if (data.contains(item.id)) {
                        data.updateItems([item]);
                      } else {
                        data.loadItems([item]);
                      }
                    }
                    if (cb != null) {
                      return cb();
                    }
                  }, 0);
                });
                subjects = (function() {
                  var _results;
                  _results = [];
                  for (s in json) {
                    if (json.hasOwnProperty(s)) {
                      _results.push(s);
                    }
                  }
                  return _results;
                })();
                that.addItemsToProcess(subjects.length);
                syncer.process(subjects, function(s) {
                  var item, ns, o, os, p, pname, prefix, ps, url, values, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
                  ps = json[s];
                  item = {
                    id: s
                  };
                  for (p in ps) {
                    os = ps[p];
                    values = [];
                    if (p === "http://www.w3.org/1999/02/22-rdf-syntax-ns#type") {
                      for (_i = 0, _len = os.length; _i < _len; _i++) {
                        o = os[_i];
                        if (o.type === "uri") {
                          for (ns in NS) {
                            prefix = NS[ns];
                            if (o.value.slice(0, ns.length) === ns) {
                              values.push(prefix + o.value.substr(ns.length));
                            }
                          }
                        }
                      }
                      item.type = values;
                    } else {
                      for (_j = 0, _len1 = os.length; _j < _len1; _j++) {
                        o = os[_j];
                        if (o.type === "literal") {
                          values.push(o.value);
                        } else if (o.type === "uri") {
                          if (o.value.substr(0, 1) === "(" && o.value.substr(-1) === ")") {
                            values.push("_:" + o.value.substr(1, o.value.length - 2));
                          } else {
                            values.push(o.value);
                          }
                        } else if (o.type === "bnode") {
                          if (o.value.substr(0, 1) === "(" && o.value.substr(-1) === ")") {
                            values.push("_:" + o.value.substr(1, o.value.length - 2));
                          } else {
                            values.push(o.value);
                          }
                        }
                      }
                      if (values.length > 0) {
                        for (ns in NS) {
                          prefix = NS[ns];
                          if (p.substr(0, ns.length) === ns) {
                            pname = prefix + p.substr(ns.length);
                            item[pname] = values;
                          }
                        }
                      }
                    }
                  }
                  if (!(item.type != null) || item.type.length === 0) {
                    item.type = 'Blank';
                  }
                  if (((_ref = item.oreisDescribedBy) != null ? _ref.length : void 0) > 0) {
                    _ref1 = item.oreisDescribedBy;
                    for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
                      url = _ref1[_k];
                      syncer.increment();
                      importFromURL(url, syncer.decrement);
                    }
                  } else {
                    items.push(item);
                  }
                  return that.addItemsProcessed(1);
                });
                return syncer.done();
              };
              itemsWithType = function(type) {
                var types;
                if (!$.isArray(type)) {
                  type = [type];
                }
                types = MITHGrid.Data.Set.initInstance(type);
                return data.getSubjectsUnion(types, "type").items();
              };
              that.getCanvases = function() {
                return itemsWithType('scCanvas');
              };
              that.getZones = function() {
                return itemsWithType('scZone');
              };
              that.getSequences = function() {
                return itemsWithType('scSequence');
              };
              that.getAnnotations = function() {
                return itemsWithType('oaAnnotation');
              };
              that.getItem = data.getItem;
              that.contains = data.contains;
              return that.importFromURL = function(url, cb) {
                return importFromURL(url, function() {
                  if (cb != null) {
                    return cb();
                  }
                });
              };
            }]));
          };
        });
      });
      SGAReader.namespace("Presentation", function(Presentation) {
        Presentation.namespace("Zone", function(Zone) {
          return Zone.initInstance = function() {
            var args, _ref;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return (_ref = MITHGrid.Presentation).initInstance.apply(_ref, ["SGA.Reader.Presentation.Zone"].concat(__slice.call(args), [function(that, container) {
              var annoExpr, options, svgRoot;
              options = that.options;
              svgRoot = options.svgRoot;
              annoExpr = that.dataView.prepare(['!target']);
              that.addLens('Image', function(container, view, model, id) {
                var height, item, rendering, svgImage, width, x, y, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
                if (__indexOf.call(options.types || [], 'Image') < 0) {
                  return;
                }
                rendering = {};
                item = model.getItem(id);
                svgImage = null;
                if ((((_ref = item.image) != null ? _ref[0] : void 0) != null) && (svgRoot != null)) {
                  x = ((_ref1 = item.x) != null ? _ref1[0] : void 0) != null ? item.x[0] : 0;
                  y = ((_ref2 = item.y) != null ? _ref2[0] : void 0) != null ? item.y[0] : 0;
                  width = ((_ref3 = item.width) != null ? _ref3[0] : void 0) != null ? item.width[0] : options.width - x;
                  height = ((_ref4 = item.height) != null ? _ref4[0] : void 0) != null ? item.height[0] : options.height - y;
                  svgImage = svgRoot.image(container, x, y, width, height, (_ref5 = item.image) != null ? _ref5[0] : void 0, {
                    preserveAspectRatio: 'none'
                  });
                }
                rendering.update = function(item) {};
                rendering.remove = function() {};
                return rendering;
              });
              that.addLens('ZoneAnnotation', function(container, view, model, id) {
                var height, rendering, width, x, y, zone, zoneContainer, zoneDataView, zoneInfo, _ref, _ref1, _ref2, _ref3;
                rendering = {};
                zoneInfo = model.getItem(id);
                zoneContainer = null;
                zoneContainer = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
                x = ((_ref = item.x) != null ? _ref[0] : void 0) != null ? item.x[0] : 0;
                y = ((_ref1 = item.y) != null ? _ref1[0] : void 0) != null ? item.y[0] : 0;
                width = ((_ref2 = item.width) != null ? _ref2[0] : void 0) != null ? item.width[0] : options.width - x;
                height = ((_ref3 = item.height) != null ? _ref3[0] : void 0) != null ? item.height[0] : options.height - y;
                $(zoneContainer).attr("x", x).attr("y", y).attr("width", width).attr("height", height);
                container.appendChild(zoneContainer);
                zoneDataView = MITHGrid.Data.SubSet.initInstance({
                  dataStore: model,
                  expressions: ['!target'],
                  key: id
                });
                zone = Zone.initInstance(zoneContainer, {
                  types: options.types,
                  dataView: zoneDataView,
                  svgRoot: svgRoot,
                  application: options.application,
                  heigth: height,
                  width: width
                });
                rendering._destroy = function() {
                  if (zone._destroy != null) {
                    zone._destroy();
                  }
                  if (zoneDataView._destroy != null) {
                    return zoneDataView._destroy();
                  }
                };
                rendering.remove = function() {
                  return rendering._destroy();
                };
                return rendering;
              });
              return that.addLens('TextContent', function(container, view, model, id) {
                var app, compileText, height, item, mods, processNode, rendering, setMod, text, textContainer, width, x, y, _ref, _ref1, _ref2, _ref3, _ref4;
                if (__indexOf.call(options.types || [], 'Text') < 0) {
                  return;
                }
                console.log("TextContent:", id);
                rendering = {};
                app = options.application();
                item = model.getItem(id);
                textContainer = null;
                textContainer = document.createElementNS('http://www.w3.org/2000/svg', 'foreignObject');
                x = ((_ref = item.x) != null ? _ref[0] : void 0) != null ? item.x[0] : 0;
                y = ((_ref1 = item.y) != null ? _ref1[0] : void 0) != null ? item.y[0] : 0;
                width = ((_ref2 = item.width) != null ? _ref2[0] : void 0) != null ? item.width[0] : options.width - x;
                height = ((_ref3 = item.height) != null ? _ref3[0] : void 0) != null ? item.height[0] : options.height - y;
                console.log(item);
                console.log("Setting up text container", x, y, width, height);
                $(textContainer).attr("x", x).attr("y", y).attr("width", width).attr("height", height);
                container.appendChild(textContainer);
                rendering.remove = function() {};
                processNode = function(info) {
                  var classes;
                  classes = [];
                  if (__indexOf.call(info.modes, 'LineAnnotation') >= 0) {
                    classes.push('line');
                  }
                  if (__indexOf.call(info.modes, 'AdditionAnnotation') >= 0) {
                    classes.push('addition');
                  }
                  if (__indexOf.call(info.modes, 'DeletionAnnotation') >= 0) {
                    classes.push('deletion');
                  }
                  if (classes.length === 0) {
                    classes.push("text");
                  }
                  return {
                    type: 'span',
                    text: info.acc,
                    classes: classes.join(' '),
                    modes: info.modes,
                    css: info.css.join(" ")
                  };
                };
                compileText = function(info) {
                  var br_pushed, current_el, i, mod, mods, offset, pos, results, text, _i, _j, _len, _ref4, _ref5;
                  text = info.text;
                  mods = info.mods;
                  offset = info.offset;
                  current_el = {
                    acc: '',
                    modes: [],
                    css: []
                  };
                  results = [];
                  br_pushed = false;
                  for (pos = _i = 0, _ref4 = text.length; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; pos = 0 <= _ref4 ? ++_i : --_i) {
                    if (!(mods[pos + offset] != null)) {
                      if (!text[pos].match(/^\s+$/)) {
                        br_pushed = false;
                      }
                      current_el.acc += text[pos];
                    } else {
                      results.push(processNode(current_el));
                      current_el.acc = text[pos];
                      _ref5 = mods[pos + offset];
                      for (_j = 0, _len = _ref5.length; _j < _len; _j++) {
                        mod = _ref5[_j];
                        if (mod.type === "LineAnnotation") {
                          if (!br_pushed) {
                            results.push({
                              type: 'br',
                              modes: [],
                              acc: '',
                              css: ''
                            });
                            br_pushed = true;
                          }
                        }
                        if (mod.action === 'start') {
                          current_el.modes.push(mod.type);
                          current_el.css.push(mod.css);
                        }
                        if (mod.action === 'end') {
                          current_el.modes = (function() {
                            var _k, _len1, _ref6, _results;
                            _ref6 = current_el.modes;
                            _results = [];
                            for (_k = 0, _len1 = _ref6.length; _k < _len1; _k++) {
                              i = _ref6[_k];
                              if (i !== mod.type) {
                                _results.push(i);
                              }
                            }
                            return _results;
                          })();
                        }
                      }
                    }
                  }
                  results.push(processNode(current_el));
                  return results;
                };
                text = "";
                mods = {};
                setMod = function(pos, pref, type, css) {
                  if ($.isArray(pos)) {
                    pos = pos[0];
                  }
                  if (mods[pos] == null) {
                    mods[pos] = [];
                  }
                  if ($.isArray(type)) {
                    type = type[0];
                  }
                  return mods[pos].push({
                    action: pref,
                    type: type,
                    css: css
                  });
                };
                app.withSource((_ref4 = item.source) != null ? _ref4[0] : void 0, function(content) {
                  var annoId, bodyEl, el, end, hitem, mode, node, nodes, rootEl, start, tags, _i, _j, _k, _len, _len1, _len2, _ref5, _ref6, _ref7;
                  text = content.substr(item.start[0], item.end[0]);
                  _ref5 = annoExpr.evaluate(item.source);
                  for (_i = 0, _len = _ref5.length; _i < _len; _i++) {
                    annoId = _ref5[_i];
                    hitem = model.getItem(annoId);
                    start = hitem.start[0];
                    end = hitem.end[0];
                    if (start <= item.end[0] && end >= item.start[0]) {
                      if (start < item.start[0]) {
                        start = item.start[0];
                      }
                      if (end > item.end[0]) {
                        end = item.end[0];
                      }
                      setMod(hitem.start, 'start', hitem.type, hitem.css);
                      setMod(hitem.end, 'end', hitem.type, '');
                    }
                  }
                  nodes = compileText({
                    text: text,
                    mods: mods,
                    offset: item.start[0]
                  });
                  tags = {};
                  bodyEl = document.createElementNS('http://www.w3.org/1999/xhtml', 'body');
                  rootEl = document.createElement('div');
                  $(rootEl).addClass("text-content");
                  $(rootEl).css("font-size", 150);
                  $(rootEl).css("line-height", 1.15);
                  bodyEl.appendChild(rootEl);
                  for (_j = 0, _len1 = nodes.length; _j < _len1; _j++) {
                    node = nodes[_j];
                    el = $("<" + node.type + " />");
                    if (node.type === "br") {
                      $(rootEl).append($("<span class='linebreak'></span>"));
                    } else {
                      el.text(node.text);
                    }
                    el.addClass(node.classes);
                    el.attr("css", node.css);
                    $(rootEl).append(el);
                    _ref6 = node.modes;
                    for (_k = 0, _len2 = _ref6.length; _k < _len2; _k++) {
                      mode = _ref6[_k];
                      if ((_ref7 = tags[mode]) == null) {
                        tags[mode] = [];
                      }
                      tags[mode].push(el);
                    }
                  }
                  return textContainer.appendChild(bodyEl);
                });
                rendering.update = function(item) {};
                return rendering;
              });
            }]));
          };
        });
        return Presentation.namespace("Canvas", function(Canvas) {
          return Canvas.initInstance = function() {
            var args, _ref;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return (_ref = MITHGrid.Presentation).initInstance.apply(_ref, ["SGA.Reader.Presentation.Canvas"].concat(__slice.call(args), [function(that, container) {
              var SVG, SVGHeight, SVGWidth, annoExpr, canvasHeight, canvasWidth, dataView, highlightDS, options, pendingSVGfctns, realCanvas, svgRoot, svgRootEl;
              options = that.options;
              highlightDS = null;
              annoExpr = that.dataView.prepare(['!target']);
              pendingSVGfctns = [];
              SVG = function(cb) {
                return pendingSVGfctns.push(cb);
              };
              svgRootEl = $("<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\"\n     xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n     width=\"0\" height=\"0\"\n >\n</svg>");
              container.append(svgRootEl);
              svgRoot = $(svgRootEl).svg({
                onLoad: function(svg) {
                  var cb, _i, _len;
                  SVG = function(cb) {
                    return cb(svg);
                  };
                  for (_i = 0, _len = pendingSVGfctns.length; _i < _len; _i++) {
                    cb = pendingSVGfctns[_i];
                    cb(svg);
                  }
                  return pendingSVGfctns = null;
                }
              });
              canvasWidth = null;
              canvasHeight = null;
              SVGHeight = null;
              SVGWidth = parseInt($(container).width() * 19 / 20, 10);
              MITHGrid.events.onWindowResize.addListener(function() {
                SVGWidth = parseInt($(container).width() * 19 / 20, 10);
                if ((canvasWidth != null) && canvasWidth > 0) {
                  return that.setScale(SVGWidth / canvasWidth);
                }
              });
              that.events.onScaleChange.addListener(function(s) {
                if ((canvasWidth != null) && (canvasHeight != null)) {
                  SVGHeight = parseInt(canvasHeight * s, 10);
                  return SVG(function(svgRoot) {
                    svgRootEl.attr({
                      width: canvasWidth,
                      height: canvasHeight
                    });
                    svgRoot.configure({
                      viewBox: "0 0 " + canvasWidth + " " + canvasHeight
                    });
                    return svgRootEl.css({
                      width: SVGWidth,
                      height: SVGHeight,
                      border: "0.5em solid #eeeeee",
                      "border-radius": "5px",
                      "background-color": "#ffffff"
                    });
                  });
                }
              });
              dataView = MITHGrid.Data.SubSet.initInstance({
                dataStore: options.dataView,
                expressions: ['!target'],
                key: null
              });
              realCanvas = null;
              return that.events.onCanvasChange.addListener(function(canvas) {
                var item, _ref, _ref1;
                dataView.setKey(canvas);
                item = dataView.getItem(canvas);
                canvasWidth = ((_ref = item.width) != null ? _ref[0] : void 0) || 1;
                canvasHeight = ((_ref1 = item.height) != null ? _ref1[0] : void 0) || 1;
                that.setScale(SVGWidth / canvasWidth);
                if (realCanvas != null) {
                  if (realCanvas.hide != null) {
                    realCanvas.hide();
                  }
                  if (realCanvas._destroy != null) {
                    realCanvas._destroy();
                  }
                }
                return SVG(function(svgRoot) {
                  svgRoot.clear();
                  return realCanvas = SGA.Reader.Presentation.Zone.initInstance(svgRoot.root(), {
                    types: options.types,
                    dataView: dataView,
                    application: options.application,
                    height: canvasHeight,
                    width: canvasWidth,
                    svgRoot: svgRoot
                  });
                });
              });
            }]));
          };
        });
      });
      SGAReader.namespace("Component", function(Component) {
        Component.namespace("ProgressBar", function(ProgressBar) {
          return ProgressBar.initInstance = function() {
            var args;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return MITHGrid.initInstance.apply(MITHGrid, ["SGA.Reader.Component.ProgressBar"].concat(__slice.call(args), [function(that, container) {
              that.events.onNumeratorChange.addListener(function(n) {
                var percent;
                percent = parseInt(100 * n / that.getDenominator(), 10);
                if (percent > 100) {
                  percent = 100;
                }
                return $(container).find(".bar").css("width", percent + "%");
              });
              that.events.onDenominatorChange.addListener(function(d) {
                var percent;
                percent = parseInt(100 * that.getNumerator() / d, 10);
                if (percent > 100) {
                  percent = 100;
                }
                return $(container).find(".bar").css("width", percent + "%");
              });
              that.show = function() {
                return $(container).show();
              };
              return that.hide = function() {
                return $(container).hide();
              };
            }]));
          };
        });
        return Component.namespace("SequenceSelector", function(SequenceSelector) {
          return SequenceSelector.initInstance = function() {
            var args, _ref;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return (_ref = MITHGrid.Presentation).initInstance.apply(_ref, ["SGA.Reader.Component.SequenceSelector"].concat(__slice.call(args), [function(that, container) {
              var options;
              options = that.options;
              that.addLens('Sequence', function(container, view, model, id) {
                var el, item, rendering, _ref;
                rendering = {};
                item = model.getItem(id);
                el = $("<option></option>");
                el.attr({
                  value: id
                });
                el.text((_ref = item.label) != null ? _ref[0] : void 0);
                return $(container).append(el);
              });
              $(container).change(function() {
                return that.setSequence($(container).val());
              });
              return that.finishDisplayUpdate = function() {
                return that.setSequence($(container).val());
              };
            }]));
          };
        });
      });
      return SGAReader.namespace("Application", function(Application) {
        return Application.namespace("SharedCanvas", function(SharedCanvas) {
          SharedCanvas.initInstance = function() {
            var args, _ref;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return (_ref = MITHGrid.Application).initInstance.apply(_ref, ["SGA.Reader.Application.SharedCanvas"].concat(__slice.call(args), [function(that) {
              var currentSequence, manifestData, options, presentations, textSource;
              options = that.options;
              presentations = [];
              manifestData = SGA.Reader.Data.Manifest.initInstance();
              that.events.onItemsProcessedChange = manifestData.events.onItemsProcessedChange;
              that.events.onItemsToProcessChange = manifestData.events.onItemsToProcessChange;
              that.getItemsProcessed = manifestData.getItemsProcessed;
              that.getItemsToProcess = manifestData.getItemsToProcess;
              that.setItemsProcessed = manifestData.setItemsProcessed;
              that.setItemsToProcess = manifestData.setItemsToProcess;
              that.addItemsProcessed = manifestData.addItemsProcessed;
              that.addItemsToProcess = manifestData.addItemsToProcess;
              textSource = SGA.Reader.Data.TextStore.initInstance();
              that.withSource = function(file, cb) {
                return textSource.withFile(file, cb);
              };
              that.addPresentation = function(config) {
                var p;
                p = SGA.Reader.Presentation.Canvas.initInstance(config.container, {
                  types: config.types,
                  application: function() {
                    return that;
                  },
                  dataView: that.dataView.canvasAnnotations
                });
                return presentations.push([p, config.container]);
              };
              currentSequence = null;
              that.events.onSequenceChange.addListener(function(s) {
                var p, seq;
                currentSequence = s;
                seq = that.dataStore.data.getItem(currentSequence);
                p = 0;
                if ((seq != null ? seq.sequence : void 0) != null) {
                  p = seq.sequence.indexOf(that.getCanvas());
                }
                if (p < 0) {
                  p = 0;
                }
                return that.setPosition(p);
              });
              that.events.onPositionChange.addListener(function(p) {
                var canvasKey, seq, _ref;
                seq = that.dataStore.data.getItem(currentSequence);
                canvasKey = (_ref = seq.sequence) != null ? _ref[p] : void 0;
                return that.setCanvas(canvasKey);
              });
              that.events.onCanvasChange.addListener(function(k) {
                var p, pp, seq, _i, _len, _results;
                that.dataView.canvasAnnotations.setKey(k);
                seq = that.dataStore.data.getItem(currentSequence);
                p = seq.sequence.indexOf(k);
                if (p >= 0 && p !== that.getPosition()) {
                  that.setPosition(p);
                }
                _results = [];
                for (_i = 0, _len = presentations.length; _i < _len; _i++) {
                  pp = presentations[_i];
                  _results.push(pp[0].setCanvas(k));
                }
                return _results;
              });
              if (options.url != null) {
                return manifestData.importFromURL(options.url, function() {
                  var annos, canvases, extractSpatialConstraint, items, seq, syncer, zones;
                  items = [];
                  syncer = MITHGrid.initSynchronizer(function() {
                    that.addItemsToProcess(1);
                    return that.dataStore.data.loadItems(items, function() {
                      return that.addItemsProcessed(1);
                    });
                  });
                  canvases = manifestData.getCanvases();
                  that.addItemsToProcess(canvases.length);
                  syncer.process(canvases, function(id) {
                    var item, mitem, _ref, _ref1;
                    that.addItemsProcessed(1);
                    mitem = manifestData.getItem(id);
                    item = {
                      id: id,
                      type: 'Canvas',
                      width: parseInt((_ref = mitem.exifwidth) != null ? _ref[0] : void 0, 10),
                      height: parseInt((_ref1 = mitem.exifheight) != null ? _ref1[0] : void 0, 10),
                      label: mitem.dctitle || mitem.rdfslabel
                    };
                    return items.push(item);
                  });
                  zones = manifestData.getZones();
                  that.addItemsToProcess(zones.length);
                  syncer.process(zones, function(id) {
                    var item, zitem, _ref, _ref1, _ref2;
                    that.addItemsProcessed(1);
                    zitem = manifestData.getItem(id);
                    item = {
                      id: id,
                      type: 'Zone',
                      width: parseInt((_ref = mitem.exifwidth) != null ? _ref[0] : void 0, 10),
                      height: parseInt((_ref1 = mitem.exifheight) != null ? _ref1[0] : void 0, 10),
                      angle: parseInt((_ref2 = mitem.scnaturalAngle) != null ? _ref2[0] : void 0, 10) || 0,
                      label: zitem.rdfslabel
                    };
                    return items.push(item);
                  });
                  seq = manifestData.getSequences();
                  that.addItemsToProcess(seq.length);
                  syncer.process(seq, function(id) {
                    var item, sitem;
                    that.addItemsProcessed(1);
                    sitem = manifestData.getItem(id);
                    item = {
                      id: id,
                      type: 'Sequence',
                      label: sitem.rdfslabel
                    };
                    seq = [];
                    seq.push(sitem.rdffirst[0]);
                    sitem = manifestData.getItem(sitem.rdfrest[0]);
                    while (sitem.id != null) {
                      seq.push(sitem.rdffirst[0]);
                      sitem = manifestData.getItem(sitem.rdfrest[0]);
                    }
                    item.sequence = seq;
                    return items.push(item);
                  });
                  extractSpatialConstraint = function(item, id) {
                    var bits, constraint;
                    if (id == null) {
                      return;
                    }
                    constraint = manifestData.getItem(id);
                    if (__indexOf.call(constraint.type, 'oaFragmentSelector') >= 0) {
                      if (constraint.rdfvalue[0].substr(0, 5) === "xywh=") {
                        item.shape = "Rectangle";
                        bits = constraint.rdfvalue[0].substr(5).split(",");
                        item.x = parseInt(bits[0], 10);
                        item.y = parseInt(bits[1], 10);
                        item.width = parseInt(bits[2], 10);
                        return item.height = parseInt(bits[3], 10);
                      }
                    }
                  };
                  annos = manifestData.getAnnotations();
                  that.addItemsToProcess(annos.length);
                  syncer.process(annos, function(id) {
                    var aitem, imgitem, item, styleItem, target, textItem, textSpan, _ref, _ref1, _ref10, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
                    that.addItemsProcessed(1);
                    aitem = manifestData.getItem(id);
                    item = {
                      id: aitem.id
                    };
                    if (aitem.oahasStyle != null) {
                      styleItem = manifestData.getItem(aitem.oahasStyle[0]);
                      if (__indexOf.call(styleItem.dcformat, "text/css") >= 0) {
                        item.css = styleItem.cntchars;
                      }
                    }
                    if (__indexOf.call(aitem.type, "scContentAnnotation") >= 0) {
                      target = manifestData.getItem((_ref = aitem.oahasTarget) != null ? _ref[0] : void 0);
                      if (__indexOf.call(target.type, "oaSpecificResource") >= 0) {
                        item.target = target.oahasSource;
                        extractSpatialConstraint(item, (_ref1 = target.oahasSelector) != null ? _ref1[0] : void 0);
                      } else {
                        item.target = aitem.oahasTarget;
                      }
                      textItem = manifestData.getItem(aitem.oahasBody);
                      if ($.isArray(textItem)) {
                        textItem = textItem[0];
                      }
                      textSpan = manifestData.getItem(textItem.oahasSelector);
                      if ($.isArray(textSpan)) {
                        textSpan = textSpan[0];
                      }
                      textSource.addFile(textItem.oahasSource);
                      item.type = "TextContent";
                      item.source = textItem.oahasSource;
                      item.start = parseInt((_ref2 = textSpan.oaxbegin) != null ? _ref2[0] : void 0, 10);
                      item.end = parseInt((_ref3 = textSpan.oaxend) != null ? _ref3[0] : void 0, 10);
                      if (id === "_:193d86c8:13b67d529fd:-40a4") {
                        console.log(item);
                      }
                    } else if (__indexOf.call(aitem.type, "sgaLineAnnotation") >= 0) {
                      textItem = manifestData.getItem(aitem.oahasTarget);
                      if ($.isArray(textItem)) {
                        textItem = textItem[0];
                      }
                      textSpan = manifestData.getItem(textItem.oahasSelector);
                      if ($.isArray(textSpan)) {
                        textSpan = textSpan[0];
                      }
                      item.target = textItem.oahasSource;
                      item.start = parseInt((_ref4 = textSpan.oaxbegin) != null ? _ref4[0] : void 0, 10);
                      item.end = parseInt((_ref5 = textSpan.oaxend) != null ? _ref5[0] : void 0, 10);
                      item.type = "LineAnnotation";
                    } else if (__indexOf.call(aitem.type, "sgaDeletionAnnotation") >= 0) {
                      textItem = manifestData.getItem(aitem.oahasTarget);
                      if ($.isArray(textItem)) {
                        textItem = textItem[0];
                      }
                      textSpan = manifestData.getItem(textItem.oahasSelector);
                      if ($.isArray(textSpan)) {
                        textSpan = textSpan[0];
                      }
                      item.target = textItem.oahasSource;
                      item.start = parseInt((_ref6 = textSpan.oaxbegin) != null ? _ref6[0] : void 0, 10);
                      item.end = parseInt((_ref7 = textSpan.oaxend) != null ? _ref7[0] : void 0, 10);
                      item.type = "DeletionAnnotation";
                    } else if (__indexOf.call(aitem.type, "sgaAdditionAnnotation") >= 0) {
                      textItem = manifestData.getItem(aitem.oahasTarget);
                      if ($.isArray(textItem)) {
                        textItem = textItem[0];
                      }
                      textSpan = manifestData.getItem(textItem.oahasSelector);
                      if ($.isArray(textSpan)) {
                        textSpan = textSpan[0];
                      }
                      item.target = textItem.oahasSource;
                      item.start = parseInt((_ref8 = textSpan.oaxbegin) != null ? _ref8[0] : void 0, 10);
                      item.end = parseInt((_ref9 = textSpan.oaxend) != null ? _ref9[0] : void 0, 10);
                      item.type = "AdditionAnnotation";
                    } else if (__indexOf.call(aitem.type, "scImageAnnotation") >= 0) {
                      imgitem = manifestData.getItem(aitem.oahasBody);
                      if ($.isArray(imgitem)) {
                        imgitem = imgitem[0];
                      }
                      item.target = aitem.oahasTarget;
                      item.label = aitem.rdfslabel;
                      item.image = imgitem.oahasSource || aitem.oahasBody;
                      item.type = "Image";
                    } else if (__indexOf.call(aitem.type, "scZoneAnnotation") >= 0) {
                      target = manifestData.getItem(aitem.oahasTarget);
                      extractSpatialConstraint(item, (_ref10 = target.hasSelector) != null ? _ref10[0] : void 0);
                      item.target = target.hasSource;
                      item.label = aitem.rdfslabel;
                      item.type = "ZoneAnnotation";
                    }
                    if (item.type != null) {
                      return items.push(item);
                    }
                  });
                  return syncer.done();
                });
              }
            }]));
          };
          return SharedCanvas.builder = function(config) {
            var manifestCallbacks, that, updateProgressTracker, updateProgressTrackerVisibility, uptv, uptvTimer, _ref;
            that = {
              manifests: {}
            };
            manifestCallbacks = {};
            updateProgressTracker = function() {};
            updateProgressTrackerVisibility = function() {};
            if (config.progressTracker != null) {
              updateProgressTracker = function() {
                var d, m, n, obj, _ref;
                n = 0;
                d = 0;
                _ref = that.manifests;
                for (m in _ref) {
                  obj = _ref[m];
                  n += obj.getItemsProcessed();
                  d += obj.getItemsToProcess();
                }
                config.progressTracker.setNumerator(n);
                return config.progressTracker.setDenominator(d || 1);
              };
              uptv = null;
              uptvTimer = 1000;
              updateProgressTrackerVisibility = function() {
                if (uptv != null) {
                  return uptvTimer = 500;
                } else {
                  uptv = function() {
                    var m, obj, _ref;
                    _ref = that.manifests;
                    for (m in _ref) {
                      obj = _ref[m];
                      if (obj.getItemsToProcess() > obj.getItemsProcessed()) {
                        config.progressTracker.show();
                        uptvTimer /= 2;
                        if (uptvTimer < 500) {
                          uptvTimer = 500;
                        }
                        setTimeout(uptv, uptvTimer);
                        return;
                      }
                    }
                    if (uptvTimer > 500) {
                      config.progressTracker.hide();
                    }
                    uptvTimer *= 2;
                    if (uptvTimer > 10000) {
                      uptvTimer = 10000;
                    }
                    return setTimeout(uptv, uptvTimer);
                  };
                  return uptv();
                }
              };
            }
            that.onManifest = function(url, cb) {
              var _ref;
              if (that.manifests[url] != null) {
                return that.manifests[url].ready(function() {
                  return cb(that.manifests[url]);
                });
              } else {
                if ((_ref = manifestCallbacks[url]) == null) {
                  manifestCallbacks[url] = [];
                }
                return manifestCallbacks[url].push(cb);
              }
            };
            that.addPresentation = function(el) {
              var manifest, manifestUrl, types, _ref;
              manifestUrl = $(el).data('manifest');
              if (manifestUrl != null) {
                manifest = that.manifests[manifestUrl];
                if (!(manifest != null)) {
                  manifest = Application.SharedCanvas.initInstance({
                    url: manifestUrl
                  });
                  that.manifests[manifestUrl] = manifest;
                  manifest.ready(function() {
                    var cb, cbs, _i, _len;
                    cbs = manifestCallbacks[manifestUrl] || [];
                    for (_i = 0, _len = cbs.length; _i < _len; _i++) {
                      cb = cbs[_i];
                      cb(manifest);
                    }
                    return delete manifestCallbacks[manifestUrl];
                  });
                  manifest.events.onItemsToProcessChange.addListener(updateProgressTracker);
                  manifest.events.onItemsProcessedChange.addListener(updateProgressTracker);
                  updateProgressTrackerVisibility();
                }
                manifest.run();
                types = (_ref = $(el).data('types')) != null ? _ref.split(/\s*,\s*/) : void 0;
                return that.onManifest(manifestUrl, function(manifest) {
                  return manifest.addPresentation({
                    types: types,
                    container: $(el)
                  });
                });
              }
            };
            if ((_ref = config["class"]) == null) {
              config["class"] = ".canvas";
            }
            $(config["class"]).each(function(idx, el) {
              return that.addPresentation(el);
            });
            return that;
          };
        });
      });
    });
  })(jQuery, MITHGrid);

  MITHGrid.defaults('SGA.Reader.Application.SharedCanvas', {
    dataStores: {
      data: {
        types: {
          Sequence: {},
          Canvas: {}
        },
        properties: {
          target: {
            valueType: 'item'
          }
        }
      }
    },
    dataViews: {
      canvasAnnotations: {
        dataStore: 'data',
        type: MITHGrid.Data.SubSet,
        expressions: ['!target']
      },
      sequences: {
        dataStore: 'data',
        types: ['Sequence']
      }
    },
    variables: {
      Canvas: {
        is: 'rw'
      },
      Sequence: {
        is: 'rw'
      },
      Position: {
        is: 'rw'
      }
    }
  });

  MITHGrid.defaults('SGA.Reader.Component.SequenceSelector', {
    variables: {
      Sequence: {
        is: 'rw'
      }
    }
  });

  MITHGrid.defaults('SGA.Reader.Component.ProgressBar', {
    variables: {
      Numerator: {
        is: 'rw',
        "default": 0
      },
      Denominator: {
        is: 'rw',
        "default": 1
      }
    },
    viewSetup: "<div class=\"progress progress-striped active\">\n  <div class=\"bar\" style=\"width: 0%;\"></div>\n</div>"
  });

  MITHGrid.defaults('SGA.Reader.Presentation.Canvas', {
    variables: {
      Canvas: {
        is: 'rw'
      },
      Scale: {
        is: 'rw'
      }
    }
  });

  MITHGrid.defaults('SGA.Reader.Data.Manifest', {
    variables: {
      ItemsToProcess: {
        is: 'rw',
        isa: 'numeric',
        "default": 0
      },
      ItemsProcessed: {
        is: 'rw',
        isa: 'numeric',
        "default": 0
      }
    }
  });

}).call(this);
